version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: patient_management_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: patient_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
